pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - author=dependabot-preview[bot]
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=codecov/patch
      - status-success=codecov/project
      - status-success=coverage/coveralls
    actions:
      merge:
        method: merge
      delete_head_branch: {}
