language: node_js

node_js:
  - '8.10'

before_install:
  - npm install -g npm

cache: npm

after_success:
  - npm run codecov
  - npm run coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master

notifications:
  email:
    on_success: change
    on_failure: always
