service: jung2bot

frameworkVersion: '>=1.40.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'dev'}
  region: ${env:REGION, 'us-east-1'}
  profile: ${env:PROFILE, ''}
  logRetentionInDays: 1
  deploymentBucket:
    serverSideEncryption: AES256
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL, 'error'}
    TELEGRAM_BOT_TOKEN: ${ssm:${self:service}-${self:provider.stage}-telegram-api-token~true}
    MESSAGE_TABLE: ${self:service}-${self:provider.stage}-messages
    MESSAGE_TABLE_GSI: ${self:custom.jung2bot.MESSAGE_TABLE_GSI}
    CHATID_TABLE: ${self:service}-${self:provider.stage}-chatIds
  tags:
    Name: jung2bot
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource: !Join
        - ''
        - - !GetAtt Jung2BotDynamoDB.Arn
          - '*'
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource: !Join
        - ''
        - - !GetAtt ChatIDsDynamoDB.Arn
          - '*'
    - Effect: Allow
      Action:
        - 'sns:Publish'
      Resource: !Ref MessagesDeadLetterTopic
    - Effect: Allow
      Action:
        - 'sns:Publish'
      Resource: !Ref OffFromWorkDeadLetterTopic

functions:
  messages:
    handler: src/handler.onMessage
    timeout: 30
    memorySize: 1024
    deadLetter:
      sns: ${self:service}-${self:provider.stage}-messages-dead-letter-topic
    events:
      - http:
          path: /
          method: post
  offFromWork:
    handler: src/handler.onOffFromWork
    timeout: 900
    memorySize: 3008
    deadLetter:
      sns: ${self:service}-${self:provider.stage}-offFromWork-dead-letter-topic
    events:
      - schedule: cron(0 10 ? * MON-FRI *) # 10 am UTC = 6 pm HKT

plugins:
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-plugin-lambda-dead-letter
  - serverless-plugin-dynamodb-autoscaling
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  jung2bot:
    MESSAGE_TABLE_GSI: chatId-dateCreated-GSI
  # serverless-domain-manager
  customDomain:
    domainName: ${env:DOMAIN}
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge
  # serverless-dynamodb-local
  dynamodb:
    start:
      seed: true
      migrate: true
    seed:
      domain:
        sources:
          - table: ${self:service}-${self:provider.stage}-messages
            sources: [./test/helper/dynamodbSeed.json]
  # serverless-plugin-dynamodb-autoscaling
  dynamodbAutoscaling:
    tablesConfig:
      Jung2BotDynamoDB:
        minCapacity: 1
        maxCapacity: 1000
      ChatIDsDynamoDB:
        minCapacity: 1
        maxCapacity: 1000

resources:
  Resources:
    # Messages DynamoDB Table
    Jung2BotDynamoDB:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: dateCreated
            AttributeType: S
          - AttributeName: chatId
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: dateCreated
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.jung2bot.MESSAGE_TABLE_GSI}
            KeySchema:
              - AttributeName: chatId
                KeyType: HASH
              - AttributeName: dateCreated
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - chatTitle
                - userId
                - username
                - firstName
                - lastName
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        SSESpecification:
          SSEEnabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        TableName: ${self:service}-${self:provider.stage}-messages
    # ChatId DynamoDB Table
    ChatIDsDynamoDB:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: N
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        TableName: ${self:service}-${self:provider.stage}-chatIds
